require("core.launch")
require("core.options")
require("core.keymaps")

spec("plugins.kanagawa")
spec("plugins.nvim-tree")
spec("plugins.bufferline")
spec("plugins.ibl")
spec("plugins.lualine")
spec("plugins.telescope")
spec("plugins.treesitter")
require("core.lazy")
